### ISSUE TITLE
environment.yml file missing for conda installation

### ISSUE THREAD

**Issue by davisidarta** [BIMSBbioinfo/pigx_scrnaseq#45]
Hello there Pigx team! 

I'm a junior bioinformatician in charge of our research group analysis and I'd like to test Pigx for analyzing some Fastq files for RNA velocity estimation (I was originally going to use DropSeq pipeline). However, I'm having some issues installing it, since GNU Guix installation was troublesome on our HPC cluster.

I then proceeded to try to install via conda. However, the environment.yml file is missing from the git source when installed by  (git clone https://github.com/BIMSBbioinfo/pigx_scrnaseq.git). I need it to run `conda env create -f environment.yml ` and proceed through conda installation of Pigx.

Any chance this can receive an update?

Cheers!

**Comment by rekado** [comment]
We don't recommend the use of Conda.  For reproducibility we recommend using Guix.

We could however welcome a patch / pull request to add `environment.yml`.
